[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-accountsdb-plugin-interface"
description = "The Solana AccountsDb plugin interface."
version = "1.9.5"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-accountsdb-plugin-interface"

[dependencies]
log = "0.4.11"
thiserror = "1.0.30"
solana-sdk = { path = "../sdk", version = "=1.9.5" }
solana-transaction-status = { path = "../transaction-status", version = "=1.9.5" }
solana-runtime = {path = "../runtime", version = "=1.9.5"}

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
